In [1]:
import numpy as np

In [3]:
ar1 = np.array([1,2,3])#array()参数是一个列表，所以得加一个[]
print(ar1)
print(type(ar1))

[1 2 3]
<class 'numpy.ndarray'>


In [4]:
ar2 = np.array(range(10))
print(ar2)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
ar3 = np.arange(21)
#0-21左闭右开
print(ar3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [6]:
ar4 = np.arange(2,20,2)
#生成一个以2起始，20结束，步长为2的一个数组
print(ar4)

[ 2  4  6  8 10 12 14 16 18]


In [7]:
print(ar4.dtype)

int32


In [14]:
import random
ar5 = np.array([random.randint(0,100) for i in range(10)])
print(ar5)

[  0  42  45  70  19  42  19  39 100  26]


In [16]:
ar6 = np.array(range(1,4),dtype=float)
print(ar6)
print(ar6.dtype)

[ 1.  2.  3.]
float64


In [18]:
ar7 = np.array(range(1,4),dtype='float32')
print(ar7)
print(ar7.dtype)

[ 1.  2.  3.]
float32


In [23]:
#调整数据类型
ar8 = ar7.astype('int8')#返回生成的指定类型的数组
print(ar8)
print(ar8.dtype)

[1 2 3]
int8


In [26]:
ar9 = np.array([random.random() for i in range(10)])
#"%.2f"%random.random()
print(ar9)
ar10 = np.round(ar9,2)
print(ar10)

[ 0.09334334  0.39455306  0.30277766  0.94596879  0.66667862  0.63696262
  0.51228641  0.82187482  0.84775891  0.08095291]
[ 0.09  0.39  0.3   0.95  0.67  0.64  0.51  0.82  0.85  0.08]
