数组可以看成维度
1维有一个0轴
2维数组有0轴，1轴
3维数组有0轴，1轴，2轴   eg.(1,2,3)中0轴表示块，1轴表示行，2轴表示列

Numpy读取csv数据集文件使用以下函数
np.loadtxt(frame,dtype=np.float,delimiter=None,skiprows=0,usecols=None,unpack=False)
frame:文件，字符串或者产生器，或者是.gz和bz2压缩文件
dtype:数据类型，可选，默认是np.float（不同于python的float）类型
delimiter:分隔字符，默认是任何空格改成 逗号
skiprows:跳过前 x 行，一般跳过表头
usecols:读取指定的列， 索引，元组类型,表示需要使用数组的哪几列
unpack: 如果为True，读入属性将分别写入不同的数组变量，False读入数据只写入一个数组变量，默认是False,使用True之后，行和列互换
csv数据集可以到https://www.kaggle.com/ 找到

In [2]:
import numpy as np
import random

In [19]:
path = 'house_rent.csv'
ar1 = np.loadtxt(path,dtype=np.int,delimiter=",",skiprows=1,usecols=(1,2,3,4,5))
print("area,rooms,bathroom,parking spaces")
print(ar1)

area,rooms,bathroom,parking spaces
[[  1 240   3   3   4]
 [  0  64   2   1   1]
 [  1 443   5   5   4]
 ..., 
 [  0  48   1   1   0]
 [  1 160   3   2   2]
 [  1  60   2   1   1]]


In [20]:
ar2 = ar1.transpose()#转置
#ar2 = ar1.T
#ar2 = ar1.swapaxes(1,0)把轴的转换，也就是行列互换
print(ar2)

[[  1   0   1 ...,   0   1   1]
 [240  64 443 ...,  48 160  60]
 [  3   2   5 ...,   1   3   2]
 [  3   1   5 ...,   1   2   1]
 [  4   1   4 ...,   0   2   1]]
