In [1]:
#将一个数组中的nan位置置换为那一列的平均值
import numpy as np

In [7]:
ar = np.round(np.random.rand(3,4)*100,2)
print(ar)

[[ 89.89  29.49  12.8   32.08]
 [ 39.67   8.62  22.83  85.37]
 [ 31.64  74.16  35.87  29.41]]


In [9]:
ar[0,1:] = np.nan
print(ar)

[[ 89.89    nan    nan    nan]
 [ 39.67   8.62  22.83  85.37]
 [ 31.64  74.16  35.87  29.41]]


In [21]:
for i in range(ar.shape[1]):
    temp_col = ar[:,i]
    nan_count = np.count_nonzero(temp_col!=temp_col)
    if nan_count!=0:
        temp_col_container = temp_col[temp_col==temp_col]#当传入[False  True  True]时，temp_col[[False  True  True]]
        print(temp_col==temp_col)
        temp_col[np.isnan(temp_col)] = temp_col_container.mean()
print(ar)

[False  True  True]
[False  True  True]
[False  True  True]
[[ 89.89  41.39  29.35  57.39]
 [ 39.67   8.62  22.83  85.37]
 [ 31.64  74.16  35.87  29.41]]


In [20]:
#例子
ar2 = ar[:,0]
print(ar2)
t = ar2[[True,False,True]]
print(t)

[ 89.89  39.67  31.64]
[ 89.89  31.64]
