行列操作，切片等
ar[a:b:c,d:e:f]
a,b,c取行，d,e,f取列，a,d分别是行和列的起始值，b,e分别是行和列的终止值，c,f分别是行和列取值的步长


ar[[a,b,c],[d,e,f]]
a,b,c表示取行的第a,b,c行
d,e,f表示取列的第d,e,f行

In [1]:
import numpy as np

In [2]:
path1 = "house_rent.csv"
ar1 = np.loadtxt(path1,dtype=np.int,delimiter=',',skiprows=1,usecols=(1,2,3,4,5))
print(ar1)

[[  1 240   3   3   4]
 [  0  64   2   1   1]
 [  1 443   5   5   4]
 ..., 
 [  0  48   1   1   0]
 [  1 160   3   2   2]
 [  1  60   2   1   1]]


In [3]:
ar2 =ar1+100
print(ar2)

[[101 340 103 103 104]
 [100 164 102 101 101]
 [101 543 105 105 104]
 ..., 
 [100 148 101 101 100]
 [101 260 103 102 102]
 [101 160 102 101 101]]


In [4]:
print(ar1[0])#获取第一行

[  1 240   3   3   4]


In [5]:
print(ar1[0:5:2])#取0到第100行
#列表[起始:结束:步长]

[[  1 240   3   3   4]
 [  1 443   5   5   4]
 [  1  19   1   1   0]]


In [6]:
#取特定行,要用两个中括号
print(ar1[[0,2,4]])

[[  1 240   3   3   4]
 [  1 443   5   5   4]
 [  1  19   1   1   0]]


In [15]:
#取列
print(ar1[1:5,0])
#表示取0-5行的所有第一列数据
#a:b:c a表示起始，b表示结束(b不取)，c表示步长，当单独出现 : 表示所有

[0 1 1 1]


In [16]:
print(ar1[:,0:2])

[[  1 240]
 [  0  64]
 [  1 443]
 ..., 
 [  0  48]
 [  1 160]
 [  1  60]]


In [18]:
#取不连续多列（用中括号）
print(ar1[0:5,[0,2,3]])
#取1-5行的第1，3，4列的数据

[[1 3 3]
 [0 2 1]
 [1 5 5]
 [1 2 2]
 [1 1 1]]


In [20]:
#取多行多列
print(ar1[[2],[3]])#取第三行第四列的值

[5]


In [23]:
print(ar1[[0,1,2],[2,3,4]])
#取(0,2)(1,3)(2,4)值

[3 1 4]


In [25]:
#print(ar1[[0,1,2],[2,3]])#错误的，不遵守广播规则