In [1]:
import numpy as np

In [4]:
tul = (2,)
#元组
print(tul)
print(type(tul))

(2,)
<class 'tuple'>


In [5]:
print(tul[0])

2


In [13]:
ar1 = np.array([[1,2],[2,3,4]])
print(ar1)
ar1.shape

[list([1, 2]) list([2, 3, 4])]


(2,)

In [20]:
ar2 = np.array([[1,3,2],[2,3,4]])
print(ar2)
print('维度是：'+str(ar2.shape))

[[1 3 2]
 [2 3 4]]
维度是：(2, 3)


In [18]:
#重置维度
ar3 = np.arange(12)
t = ar3.reshape((3,4))#重置为三行四列。。。。三维,reshape有返回值，且ar3调用这个方法之后不会被改变
print(ar3)
print(t)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
ar4 = np.arange(24).reshape(3,2,4)
#3可以理解为分成3个矩阵，2，4表示每个矩阵是2X4的
print(ar4)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]


In [24]:
ar5 = ar4.reshape((24,1))#24行1列
print(ar5)
ar6 = ar4.reshape((1,24))
print(ar6)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]
 [17]
 [18]
 [19]
 [20]
 [21]
 [22]
 [23]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]]


In [28]:
#获取总数
sum = ar4.shape[0]*ar4.shape[1]*ar4.shape[2]#块乘以行乘以列
print(sum)
#或者
sum2 = ar4.flatten()
print(sum2)

24
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [29]:
#numpy的算法
print(ar4)
print(ar4*2)
print(ar4+2)
print(ar4/2)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
[[[ 0  2  4  6]
  [ 8 10 12 14]]

 [[16 18 20 22]
  [24 26 28 30]]

 [[32 34 36 38]
  [40 42 44 46]]]
[[[ 2  3  4  5]
  [ 6  7  8  9]]

 [[10 11 12 13]
  [14 15 16 17]]

 [[18 19 20 21]
  [22 23 24 25]]]
[[[  0.    0.5   1.    1.5]
  [  2.    2.5   3.    3.5]]

 [[  4.    4.5   5.    5.5]
  [  6.    6.5   7.    7.5]]

 [[  8.    8.5   9.    9.5]
  [ 10.   10.5  11.   11.5]]]


In [30]:
#除以0的话
print(ar4/0)
#nan表示none of number
#inf是infinite表示无限，一个数字除以0的极限是无穷

[[[ nan  inf  inf  inf]
  [ inf  inf  inf  inf]]

 [[ inf  inf  inf  inf]
  [ inf  inf  inf  inf]]

 [[ inf  inf  inf  inf]
  [ inf  inf  inf  inf]]]


C:\Users\ZZE-LapTop\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  
C:\Users\ZZE-LapTop\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
