 numpy数值的修改
 直接取值之后赋值

In [2]:
import numpy as np
import random as rd

In [6]:
ar = np.array([rd.randint(0,100) for i in range(20)]).reshape(2,10)
print(ar)

[[81 83 37 89 84 14 66  4 73 51]
 [43  4 38 12 99  8 58 17  0 62]]


In [12]:
ar[ar<10]=10  #获取所有小于10的值，并且把所有小于10的值设置为10
print(ar)

[[81 83 37 89 84 14 66 10 73 51]
 [43 10 38 12 99 10 58 17 10 62]]


In [14]:
print(ar<20)

[[False False False False False  True False  True False False]
 [False  True False  True False  True False  True  True False]]


In [16]:
#另外一种方法
ar2 = np.where(ar<20,0,10)#相当于三目运算，np.where(a<b,c,d) 差不多是 a<b?c:d
print(ar2)

[[10 10 10 10 10  0 10  0 10 10]
 [10  0 10  0 10  0 10  0  0 10]]


In [17]:
#还有一种 在某个范围内修剪的函数
ar3 = ar.clip(20,80)
#小于20则换为20，大于80则换位80
print(ar3)

[[80 80 37 80 80 20 66 20 73 51]
 [43 20 38 20 80 20 58 20 20 62]]
