nan:not a number  
inf:positive infinite
-inf:negative infinite

In [2]:
import numpy as np

In [3]:
a = np.inf
b = np.nan
print(a,b)

inf nan


In [4]:
c = np.nan
print(b==c)#两个不同的nan是不相等的

False


In [9]:
ar1 = np.arange(2,14).reshape(3,4)
print(ar1)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


In [10]:
print(np.count_nonzero(ar1))#获取数组非0的个数

12


In [41]:
ar2 = np.array([[np.nan,1,2,3,4,5],[1,2,3,4,5,6]])
print(ar2)

[[ nan   1.   2.   3.   4.   5.]
 [  1.   2.   3.   4.   5.   6.]]


In [25]:
count = np.count_nonzero(ar2!=ar2)#此方法可以算出一个数组里面有多少个nan
print(ar2!=ar2,"\n",count)#对比之后，由于两个nan是不相同的，在和自己对比的前提下，只有nan和nan对比会出现True也就是1，而False是0

[[ True False False False False False]
 [False False False False False False]] 
 1


In [26]:
#此外判断是否是nan还可以直接用函数
print(np.isnan(ar2))
print(np.count_nonzero(np.isnan(ar2)))

[[ True False False False False False]
 [False False False False False False]]
1


In [27]:
t = np.nan*20
print(t)#nan和任何值进行运算都会是nan

nan


In [47]:
#所以当一个数组中存在nan，则调用函数np.sum会得出nan
t = np.sum(ar2,axis=0)#计算行之和
print(ar2,'\n.............\n',t)

[[ nan   1.   2.   3.   4.   5.]
 [  1.   2.   3.   4.   5.   6.]] 
.............
 [ nan   3.   5.   7.   9.  11.]


In [38]:
np.sum(ar2)#计算数组所有数值之和

nan

In [39]:
t = np.sum(ar2,axis=1)#计算列
print(ar2,'\n',t)

[[ nan   1.   2.   3.   4.   5.]
 [  1.   2.   3.   4.   5.   6.]] 
 [ nan  21.]


In [42]:
#或者
print(ar2.sum(axis=0))#axis表示以行为基准，竖直计算

[ nan   3.   5.   7.   9.  11.]


In [43]:
print(ar2.sum(axis=1))#axis表示以列为基准，水平计算

[ nan  21.]
