一些计算函数
a = np.array([1,2,3])
a.sum(axis=None)
a.mean(axis=None)
np.median(a,axis=None)
a.max(axis=None)
a.min(axis=None)
np.ptp(a,axis=None)  求极值
a.std(axis=None)     求标准差

axis表示以哪一个为基准，求他垂直方向的那一行或者列
axis=0表示以行为基准，向下计算或者求值


In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1,3,5,2],[1,2,6,7]])
print(ar1)

[[1 3 5 2]
 [1 2 6 7]]


In [4]:
print(ar1.max(axis=0))

[1 3 6 7]


In [5]:
print(ar1.max(axis=1))

[5 7]
