In [3]:
import numpy as np
import random as rd

In [6]:
ar1 = np.array([rd.randrange(0,20) for i in range(20)]).reshape(2,2,5)
print(ar1)
print(".....................")
ar2 = np.array([rd.randrange(0,20) for i in range(20)]).reshape(2,2,5)
print(ar2)

[[[ 2 17 17 14  0]
  [ 4 14  8  6 15]]

 [[ 8 13 13 11 17]
  [14  9 14  1  1]]]
.....................
[[[19  3 13  4 17]
  [ 9 15  1 13  6]]

 [[ 9  6  6  2  2]
  [ 7  7 13 11  7]]]


In [7]:
print(ar1+ar2)

[[[21 20 30 18 17]
  [13 29  9 19 21]]

 [[17 19 19 13 19]
  [21 16 27 12  8]]]


In [9]:
ar3 = np.arange(2,20,2).reshape(3,3)
print(ar3)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [12]:
ar4 = np.arange(1,4).reshape(1,3)
print(ar4)

[[1 2 3]]


In [14]:
print(ar3+ar4)
print(ar3*ar4)
print(ar3-ar4)
print(ar3/ar4)

[[ 3  6  9]
 [ 9 12 15]
 [15 18 21]]
[[ 2  8 18]
 [ 8 20 36]
 [14 32 54]]
[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]
[[  2.   2.   2.]
 [  8.   5.   4.]
 [ 14.   8.   6.]]


#计算中遵循广播原则

In [15]:
#(3,2)和(3,3)是无法相乘的
ar5 = np.arange(0,6).reshape(3,2)
ar6 = np.arange(0,9).reshape(3,3)
print(ar5*ar6)

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [18]:
ar5 = np.arange(0,6).reshape(2,3)
ar6 = np.arange(0,9).reshape(3,3)
print(ar5*ar6)

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 

In [22]:
ar5 = np.arange(0,6).reshape(2,3)
print(ar5)
print('......................')
ar6 = np.arange(0,12).reshape(2,2,3)
print(ar6)
print('......................')
print(ar5*ar6)

[[0 1 2]
 [3 4 5]]
......................
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
......................
[[[ 0  1  4]
  [ 9 16 25]]

 [[ 0  7 16]
  [27 40 55]]]
