In [1]:
import tensorflow as tf

tf.linspace(start, end, num)
start代表起始的值
end表示结束的值
num表示在这个区间里生成数字的个数
生成的数组是等间隔生成的
start和end这两个数字必须是浮点数，不能是整数，如果是整数会出错的

In [12]:
x = tf.linspace(-6., 6., 10)
x.shape

TensorShape([10])

In [4]:
#  调用sigmoid激活函数
tf.nn.sigmoid(x)#取值范围可以压缩到0-1

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.00247262, 0.00931596, 0.0344452 , 0.11920292, 0.33924368,
       0.6607564 , 0.880797  , 0.96555483, 0.99068403, 0.9975274 ],
      dtype=float32)>

In [5]:
#调用relu函数
tf.nn.relu(x)#relu=max(0,x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.      , 0.      , 0.      , 0.      , 0.      , 0.666667,
       2.      , 3.333334, 4.666667, 6.      ], dtype=float32)>

In [6]:
#调用LeakyReLU函数
tf.nn.leaky_relu(x,alpha=0.1)#alpha代表参数p

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.6       , -0.46666667, -0.33333334, -0.2       , -0.06666666,
        0.666667  ,  2.        ,  3.333334  ,  4.666667  ,  6.        ],
      dtype=float32)>

In [9]:
#创建leakyrelu网络层
from tensorflow.keras import layers
layers.LeakyReLU(0.1)

In [10]:
#调用tanh激活函数
tf.nn.tanh(x)

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([-0.9999877 , -0.99982315, -0.997458  , -0.9640276 , -0.58278286,
        0.5827831 ,  0.9640276 ,  0.997458  ,  0.99982315,  0.9999877 ],
      dtype=float32)>

In [16]:
#调用softmax函数
z = tf.constant([2., 3., 5.])
tf.nn.softmax(z)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.04201007, 0.1141952 , 0.8437947 ], dtype=float32)>

In [17]:
#创建softmax网络层
z = tf.random.normal([2,10])#创建一个2x10的输出层
y_onehot = tf.constant([1,3])# 创建两个输出
y_onehot = tf.one_hot(y_onehot, depth=10)#对两个输出进行one hot编码，进而得到一下2x10的矩阵
y_onehot

<tf.Tensor: shape=(2, 10), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

onehot编码参考资料https://www.cnblogs.com/shuaishuaidefeizhu/p/11269257.html

In [34]:
#在tensoflow中提供了softmax和交叉熵同时实现的函数
from tensorflow import keras
loss = keras.losses.categorical_crossentropy(y_onehot,z,from_logits=True)#可以实现对输出层z的softmax以及和给定标签值计算交叉熵
loss = tf.reduce_mean(loss)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=3.1853447>

In [35]:
#或者创建一个softmax和交叉熵的实例
criteon = keras.losses.CategoricalCrossentropy(from_logits=True)
loss = criteon(y_onehot,z)
loss

<tf.Tensor: shape=(), dtype=float32, numpy=3.1853447>