In [1]:
import torch

In [2]:
x = torch.empty(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [17]:
x = torch.rand(3, 4)
print(x)

tensor([[0.4200, 0.4274, 0.7934, 0.4218],
        [0.0122, 0.0946, 0.9418, 0.9294],
        [0.7829, 0.7269, 0.6107, 0.4178]])


In [18]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


In [19]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [20]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [21]:
x = torch.randn_like(x,dtype=torch.double)
print(x)

tensor([[-1.5328, -0.0022,  0.0890],
        [ 0.0095,  0.6502,  0.8590],
        [-0.2227, -0.4424,  1.7802],
        [ 0.5100, -1.6297, -1.3229],
        [-0.0450, -0.2807,  1.7582]], dtype=torch.float64)


In [22]:
print(x.size())

torch.Size([5, 3])


In [24]:
y = torch.rand(5,3)
print(x+y)
print(torch.add(x,y))

tensor([[-0.9122,  0.2270,  0.1589],
        [ 0.9377,  0.7080,  0.9902],
        [ 0.0304, -0.1158,  1.8596],
        [ 1.0041, -1.1400, -0.3902],
        [ 0.2012, -0.0057,  2.7234]], dtype=torch.float64)
tensor([[-0.9122,  0.2270,  0.1589],
        [ 0.9377,  0.7080,  0.9902],
        [ 0.0304, -0.1158,  1.8596],
        [ 1.0041, -1.1400, -0.3902],
        [ 0.2012, -0.0057,  2.7234]], dtype=torch.float64)


In [25]:
result = torch.empty(5,3)
result = x+y
print(result)
torch.add(x, y, out=result)
result

tensor([[-0.9122,  0.2270,  0.1589],
        [ 0.9377,  0.7080,  0.9902],
        [ 0.0304, -0.1158,  1.8596],
        [ 1.0041, -1.1400, -0.3902],
        [ 0.2012, -0.0057,  2.7234]], dtype=torch.float64)


tensor([[-0.9122,  0.2270,  0.1589],
        [ 0.9377,  0.7080,  0.9902],
        [ 0.0304, -0.1158,  1.8596],
        [ 1.0041, -1.1400, -0.3902],
        [ 0.2012, -0.0057,  2.7234]], dtype=torch.float64)

In [26]:
y

tensor([[0.6205, 0.2292, 0.0699],
        [0.9282, 0.0578, 0.1313],
        [0.2531, 0.3265, 0.0795],
        [0.4940, 0.4897, 0.9327],
        [0.2462, 0.2750, 0.9652]])

In [27]:
y.add_(x)
y#改变y的值

tensor([[-0.9122,  0.2270,  0.1589],
        [ 0.9377,  0.7080,  0.9902],
        [ 0.0304, -0.1158,  1.8596],
        [ 1.0041, -1.1400, -0.3902],
        [ 0.2012, -0.0057,  2.7234]])

In [28]:
print(y[1:3,:2])

tensor([[ 0.9377,  0.7080],
        [ 0.0304, -0.1158]])


In [30]:
#改变大小
x.size()

torch.Size([5, 3])

In [31]:
t = x.view(15)

In [33]:
print(t.size())

torch.Size([15])


In [34]:
t = t.view(3,5)
t.size()

torch.Size([3, 5])

In [39]:
#获取元素
a = torch.randn(1)
print(a)
print(a.item())

tensor([-0.3528])
-0.3527720868587494
